language: python
cache:
  directories:
  - "$PIP_CACHE_DIR"
  - "$PIPENV_CACHE_DIR"
branches:
  except:
  - master
env:
  global:
  - PIP_CACHE_DIR=$HOME/.cache/pip
  - PIPENV_CACHE_DIR=$HOME/.cache/pipenv
matrix:
  fast_finish: true
  include:
  - name: Conda on Windows
    os: windows
    language: shell
    env:
    - PATH="/c/tools/miniconda3/:/c/tools/miniconda3/Library/mingw-w64:/c/tools/miniconda3/Library/usr/bin:/c/tools/miniconda3/Library/bin:/c/tools/miniconda3/Scripts:/c/tools/miniconda3/bin:$PATH"
    - PBIN=pip
    - PRUN=
    before_install:
    - choco install miniconda3 openssl.light nsis
    - conda config --set always_yes yes --set changeps1 no
    - conda update -n base -c defaults conda python
    - conda create -q -n test python=$TRAVIS_PYTHON_VERSION
    - source activate test
    - python -m pip install --upgrade pip
    install:
    - pip install pipenv
    - pipenv lock -r | tail -n +2  > requirements.txt
    - pip install -r requirements.txt
    - pipenv lock -r --dev | tail -n +2 > requirements.txt
    - pip install -r requirements.txt
    - conda list
    - pip list
before_script:
- |
  if [[ -n ${TRAVIS_TAG} ]]
  then
    echo $TRAVIS_TAG > src/VERSION
  fi
script:
- echo "Look ma no tests"
before_deploy:
- $PRUN $PBIN install pyinstaller pywin32
- $PRUN pyinstaller --clean --log-level=INFO -F pyjvcpj.spec
- |
  if [[ -n "${PRUN}" ]]
  then
      mv dist/pyjvcpj.exe dist/pyjvcpj_small.exe
  fi
deploy:
  provider: releases
  api_key:
    secure: SPn6Zx2ud6OpcexAMK6760ZuWe0tDbK6k9uXPD6aI2ZHB1OxLAblILNqjCtGniZ8Vniqz3d00Lt3aUt/OxKFUDEenzjv2PdtryzYsFNV2146U56m/uetwIVr4D2UNM2ClhXiRYYHWbZnKXg/1ZlOx560gYyBegHDRLCYcONCZ5VPP2JfpOZXMPoRD+nqEVywdIHPuompb1FotZwZxni2sBZhluUOj2ipQc4NLwfi9B8VCEkdRjSCvMOPb9NPWrDIvFkbqgZg2in79pYX1dwkuocLHXVZbFL8VRFCPBl5ypxxnXtYgphOfkR4PSk47qg/hddtMloqchhjoGwMLJNg+DuswfhtiJ13AcgR9GMqacrK+mraXgCVOAMGHvBpAfL9a0AIyEWZgijmNBYhgn063KL86Porv647WHjFc1+a1qk0fFEfsjFJ75Tgj/BWUowUaDP33dlDfviK401wzJG/ubFsrD+V7bNNm5BGBHemjCR7OPF3OaRMzTicskW3clWAw8V7fVeoaqrvVpmNDNxtJoFPboS1eoluxf+a8rFa1eCf9hTbQCzAa6hXaN3dRhvMx7XEd3VjTw1DSyUqmMJdx6DFMZYD55sNWXBy6kKt8fScbHRNTMGBN5zGLcO1D0hiHQ35VNeO9Ef9UalDMJH4BUUIjuf2dh/e6R7FnuGxrtQ=
  file_glob: true
  file: dist/pyjvcpj*.exe
  on:
    repo: 3ll3d00d/pyjvcpj
    tags: true
  skip_cleanup: true
  prerelease: true
